### ISSUE TITLE
can not find some head file

### ISSUE THREAD

**Issue by LebronJames0423** [iwatake2222/aiine_transform#1]
hello，when i follow your Using Tutorials (https://bestofcpp.com/repo/iwatake2222-aiine_transform), after successfully compile in vs2017, and i open the build folder in vs2017, first it tell me that there is no tensorflow,and i download it from https://github.com/tensorflow/tensorflow,and put it in
![image](https://user-images.githubusercontent.com/33833521/147715663-23347526-7cd0-4767-9d83-6b46e2b6a511.png)
,and then , after compile successfully  again , it through another problem 
![image](https://user-images.githubusercontent.com/33833521/147715715-489a0190-9a89-4f57-aef6-5f08eb7c9c19.png)
,that is "Aiine Transform\aiine_transform\inference_helper\third_party\cmakes\..\tensorflow\tensorflow/lite/interpreter_builder.h(26): fatal error C1083: 无法打开包括文件: “flatbuffers/flatbuffers.h”: No such file or directory".  
 can you tell me how to slove this? thank you very much.

**Comment by iwatake2222** [comment]
Probably you missed the following commands, or it failed. Please make sure the download process succeeds when you run `download_dependencies.sh`

```
cd inference_helper/third_party/tensorflow
chmod +x tensorflow/lite/tools/make/download_dependencies.sh
tensorflow/lite/tools/make/download_dependencies.sh
```

**Comment by LebronJames0423** [comment]
> Probably you missed the following commands, or it failed. Please make sure the download process succeeds when you run `download_dependencies.sh`
> 
> ```
> cd inference_helper/third_party/tensorflow
> chmod +x tensorflow/lite/tools/make/download_dependencies.sh
> tensorflow/lite/tools/make/download_dependencies.sh
> ```
thank for your reply,
i run your project in win10, after follow your device, i find the "download_dependencies.sh" in mediapipe folder,and i put it in the following folder
![image](https://user-images.githubusercontent.com/33833521/147719430-9a52f62f-3d15-477c-b0ea-66957152a161.png)
,and run the "chmod +x tensorflow/lite/tools/make/download_dependencies.sh" in cmd 
![image](https://user-images.githubusercontent.com/33833521/147719556-6aa1e2ef-2769-4c02-9169-02a09098fcf4.png)
, and after do this , i compile it again in cmake 
![image](https://user-images.githubusercontent.com/33833521/147719576-9e6a925b-45c6-4330-a14f-3ca09d5606e8.png)
but the problem still there, is there anything wrong with my operations?
by the way, can you upload your compiled vs project in your github? thank you very much~

**Comment by LebronJames0423** [comment]
> download_dependencies.sh

should i compile tensorflow lite in win10 and put it in your project before i compile your project？

**Comment by iwatake2222** [comment]
I don't think you follow the instruction.
Please read this section carefully.

https://github.com/iwatake2222/aiine_transform#download

**Comment by LebronJames0423** [comment]
> I don't think you follow the instruction. Please read this section carefully.
> 
> https://github.com/iwatake2222/aiine_transform#download

i successfully compiled it ,and it works well in vs2017 in win10, thank you.  But i have another problem : The face mesh module of mediapipe includes model inference and pre- and post-processing. The pre- and post-processing code is written in C++. Did you extracted the code  or wrote it by yourself? thanks a lot.

**Comment by iwatake2222** [comment]
👍

I don't understand what you mean by `extract` , but I referred to https://github.com/google/mediapipe/blob/master/docs/solutions/face_mesh.md#output , then I wrote it in C++ by myself.

**Comment by LebronJames0423** [comment]
> 👍
> 
> I don't understand what you mean by `extract` , but I referred to https://github.com/google/mediapipe/blob/master/docs/solutions/face_mesh.md#output , then I wrote it in C++ by myself.

your work is really a cool job! 
why i run your project:
i  want to use the face mesh model of mediapipe. it really quick when inferencing ,but i do not want to use mediapipe framework and tensorflow lite engine, i want to use another engine ,mindspore. what i did last few days is that i followed the mediapipe framework 
![image](https://user-images.githubusercontent.com/33833521/147741625-39c019c0-9e3d-4395-9bcc-78e80165d04f.png)
,to extract the code of pre and post processing the result of face_landmark.tflite model. that's what i mean "extract" . but the result keypoints is not Accurate. so i want to confirm why the results is not accurate,  the inference results is not accurate or pre and post processing code is not right, so after i find your blog, i think i maybe helpful for me, and it do. 
next i will see how you write this project.

**Comment by iwatake2222** [comment]
> i do not want to use mediapipe framework and tensorflow lite engine, 

Really understood!!
I prefer not using heavy frameworks, too.

Porting pre/post logic to your project might be challenging, but hope my code helps.
Good luck
